# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 07:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('createddate', models.DateTimeField(default=datetime.datetime(2016, 7, 2, 7, 47, 7, 101674))),
            ],
        ),
    ]
